# Generated by Django 3.2.9 on 2021-11-23 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TiresInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trim_id', models.IntegerField()),
                ('front_width', models.IntegerField()),
                ('front_profile', models.IntegerField()),
                ('front_rim', models.IntegerField()),
                ('rear_width', models.IntegerField()),
                ('rear_profile', models.IntegerField()),
                ('rear_rim', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tires_info',
            },
        ),
    ]
